### ISSUE TITLE
S3 config recommendation

### ISSUE THREAD

**Issue by devth** [antunderwood/bcms_s3#2]
I'd recommend following the convention that paperclip and s3_swf_upload follow, providing separate buckets for test, dev and prod:

http://github.com/nathancolgate/s3-swf-upload-plugin/blob/master/lib/s3_swf_upload/railties/generators/uploader/templates/amazon_s3.yml

**Comment by antunderwood** [comment]
Using the method in austinmoore's fork you can now
a) keep your AWS keys secret and 
b) by having different environmental variables on heroku or locally mimic having different s3 variables in development and production - see  the [documentation](http://github.com/aunderwo/bcms_s3/blob/master/README.markdown)
