### ISSUE TITLE
Merge changes from network and republish gem

### ISSUE THREAD

**Issue by devth** [antunderwood/bcms_s3#3]
Can you merge some of the great work done on the bcms_s3 forks and re-publish the gem? If bcms worked with bundler it wouldn't be a problem but I haven't been able to get it working so far..

**Comment by antunderwood** [comment]
Sure I will try and get on to this as soon as I can.

**Comment by devth** [comment]
Awesome, thanks. Looks like austinmoore's fork at http://github.com/austinmoore has all the latest code. I think this fixes the other [issue I opened regarding unpublished attachments](http://github.com/aunderwo/bcms_s3/issues#issue/1) as well.

**Comment by antunderwood** [comment]
I have merged the code from austinmoore's fork and published a new version of the gem 0.2.0
