### ISSUE TITLE
Unitialized constant Cms::AttachmentsController with browsercms-3.1.2

### ISSUE THREAD

**Issue by mezza** [antunderwood/bcms_s3#5]
Just noticed that on a new box with browsercms-3.1.2 that the db:migrate rake task was failing.

Only solution was to also install the older 3.1.0 version as well.

rake trace here: http://gist.github.com/478500

**Comment by antunderwood** [comment]
Hmmm strange can't see any significant changes between 3.1.0 and 3.1.2 that could account for it. On a fresh install of the browsercms demo app, I can't replicate the error.

At what stage did you perform the db:migrate task?

best wishes, Anthony
